### ISSUE TITLE
Unable to update offset

### ISSUE THREAD

**Issue by Legsbiter** [LeonBlade/PaisleyPark#16]
Hello,

I'm trying to update my offsets for 5.2 patch and I keep getting an error saying it wasn't able to fetch from the server.

Here's the error I get from my logs

2020-02-18 05:47:04.4758 Couldn't fetch or save offsets from the server! System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at PaisleyPark.ViewModels.MainWindowViewModel.GetOffsets()

**Comment by LeonBlade** [comment]
Update isn't available, that's why.
