### ISSUE TITLE
"Something happened while injecting into Final Fantasy XIV"

### ISSUE THREAD

**Issue by SirVG** [LeonBlade/PaisleyPark#5]
Using 1.3.6. Every time I run the program, I get that message and the program halts.

This prints in the Error.Log.

2019-06-20 11:01:57.0544 Injection Failed! newmem: 0x7F77FFB0000, inject: 0x0 System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PaisleyPark.Common.AsmjitCSharp.Native_Assembler(String input, IntPtr& addr, Int32& size)
   at PaisleyPark.Common.AsmjitCSharp.Assemble(String input)
   at PaisleyPark.ViewModels.MainWindowViewModel.InjectCode()

**Comment by LeonBlade** [comment]
Do you have a 32-bit OS?

**Comment by SirVG** [comment]
Running Windows 8 Pro 64-bit and DX11 of FFXIV.

**Comment by LeonBlade** [comment]
Can you try downloading a fresh copy of 1.3.6 and try again?  I just did so myself, and had no issues running and injecting into FFXIV.

**Comment by SirVG** [comment]
Tried a fresh copy on that computer, no luck, same error.

Tried it on a different computer (Win 8.1 64-bit, DX11), no issues.

So not sure why my main computer for playing FFXIV is causing issues and hoping you have an idea.

**Comment by LeonBlade** [comment]
It's hard to say, but your error is specifically about architecture types being mismatched, which is why I asked you about if you had a 32-bit OS.  Is there any chance you can upgrade to Windows 10?  I can't really ensure that Windows 8 will function properly as I have no way of testing that operating system.
